version: '3.4'

services:
  tcs:
    image: tcs
    build:
      context: test-communication-service
      target: production
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    expose: 
      - 3000

  validation-service:
    image: validation-service
    build:
      context: validation-service
      target: production
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
